# Generated by Django 5.1.7 on 2025-04-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='handwritingimage',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='handwritingimage',
            name='recognized_text',
            field=models.TextField(blank=True),
        ),
    ]
