# Generated by Django 5.1.7 on 2025-04-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0002_handwritingimage_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handwritingimage',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to='processed/'),
        ),
    ]
