# Generated by Django 5.1.7 on 2025-04-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0003_handwritingimage_processed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='handwritingimage',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
